version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: packages/app/Dockerfile
    container_name: null
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3000:3000
  cron:
    build:
      context: ..
      dockerfile: packages/cron/Dockerfile
    container_name: null
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
  doc:
    build:
      context: ..
      dockerfile: packages/docs/Dockerfile
    container_name: null
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3001:3000
    volumes:
      - .:/docs/.docusaurus
  db:
    image: postgres:latest
    container_name: null
    restart: unless-stopped
    volumes:
      - null
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: null
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - null
    ports:
      - 6379:6379
volumes: null
