version: "3.8"
services:
  app:
    image: DOCKER_DEPLOY_APP_IMAGE
    container_name: sermin_app
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3000:3000
  wss:
    image: DOCKER_DEPLOY_WSS_IMAGE
    container_name: sermin_wss
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3001:3001
  cron:
    image: DOCKER_DEPLOY_CRONS_IMAGE
    container_name: sermin_crons
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
  doc:
    image: DOCKER_DEPLOY_DOCS_IMAGE
    container_name: sermin_doc
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 3001:3000
    volumes:
      - .:/docs/.docusaurus
  db:
    image: postgres:latest
    container_name: sermin_db
    restart: unless-stopped
    volumes:
      - sermin-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: sermin_redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - sermin-redis-data:/data
    ports:
      - 6379:6379
volumes:
  sermin-postgres-data: null
  sermin-redis-data: null
